print("***********")
print("Hamburguesas El Corral")
print("***********")
nombreUsuario=input("Digite el nombre del usuario: ")
cedulaUsuario=input("Digite la cedula del usuario: ")
pedidoUsuario=input("Nombre de la hamburguesa: ")
cantidadPedido=int(input("Cantidad de hamburguesas: "))
valorPedido=int(input("Valor de hamburguesa: "))
print("***********")
print("***********")
print(pedidoUsuario)
print(cantidadPedido)
print("El valor total de su pedido es: ")
print(valorPedido*cantidadPedido)